//@ts-check
export const Shapes =
{
    default: "default",
    invis: "invis",
    record: "record",
    doublecircle: "doublecircle",
    box: "box",
    rect: "rect",
    rectangle: "rectangle",
    square: "square",
    roundedbox: "roundedbox",
    dots: "dots",
    circle: "circle",
    ellipse: "ellipse",
    diamond: "diamond",
    minidiamond: "minidiamond",
    minisquare: "minidiamond",
    note: "note",
    mail: "mail",
    cloud: "cloud",
    actor: "actor",
    beginpoint: "beginpoint",
    endpoint: "endpoint",
    condition: "condition",
    database: "database",
    terminator: "terminator",
    input: "input",
    loopin: "loopin",
    loop: "loop",
    loopstart: "loopstart",
    loopout: "loopout",
    loopend: "loopend",
};
